//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wine_e_commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorize
    {
        public int idChucNang { get; set; }
        public int idKhachHang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual my_Funtion my_Funtion { get; set; }
    }
}
