//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wine_e_commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ItemCarts = new HashSet<ItemCart>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaDonHang { get; set; }
        [DisplayName("Phương thức thanh toán")]
        public string PhuongThucThanhToan { get; set; }
        [DisplayName("Tổng sản phẩm")]
        public Nullable<int> TongSanPham { get; set; }
        [DisplayName("Địa chỉ nhận hàng")]
        public string DiaChiNhanHang { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        [DisplayName("Ngày đặt")]
        public Nullable<System.DateTime> ngayDat { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemCart> ItemCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
