//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wine_e_commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class GioHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GioHang()
        {
            this.ItemCarts = new HashSet<ItemCart>();
        }
    
        public int MaGioHang { get; set; }
        [DisplayName("Số loại sản phẩm")]
        public Nullable<int> SoLoaiSanPham { get; set; }
        [DisplayName("Ngày thêm")]
        public Nullable<System.DateTime> NgayThem { get; set; }
        public Nullable<int> idKhachHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemCart> ItemCarts { get; set; }
    }
}
